version: '3'
services:
  db:
    image: mysql:latest
    container_name: rvm_app
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=belajar
      - MYSQL_DATABASE=rvm_app
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
