import './globals.css';
import { Poppins } from 'next/font/google';
import ClientLayout from './client-layout';
import { LocationProvider } from '@/context/location';
import { UserProvider } from '@/context/user';

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} `}>
        <LocationProvider>
          <UserProvider>
            {/* <BottleProvider> */}
              <ClientLayout>
                <main>{children}</main>
              </ClientLayout>
            {/* </BottleProvider> */}
          </UserProvider>
        </LocationProvider>
      </body>
    </html>
  );
}
